#!/usr/bin/python
import os
import sys

CSCANSYS = "/scratch/foldenauer/code/cscan"

fullfile = sys.argv[1]
#Check whether inputfile was given with absolute path
if fullfile[0] !='/':
  fullfile = os.getcwd() + "/" +   fullfile
print  fullfile

#Cd into cscan directoy
os.chdir(CSCANSYS)
os.system("./bin/core %s"%fullfile)
